### ISSUE TITLE
php8 only ?

### ISSUE THREAD

**Issue by skoro** [skoro/php-tkui#4]
Using PHP8 gives the following improvements:
- nullsafe operator `?->` (`HasLogger`)
- constructor property promotions
- using Enums instead of consts
- union types: `array|Options` in widget constructors

**Comment by CViniciusSDias** [comment]
There are already features of PHP 8 being used (like `Stringable`): https://github.com/skoro/php-tkui/blob/master/src/Image.php#L5

So the component already depends on PHP 8. :-)
Go for it.

**Comment by skoro** [comment]
Thank you ! I will remove all the PHP8 features to stay compatible with 7.4 as it's declared in `composer.json` now.

**Comment by CViniciusSDias** [comment]
PHP 7.4 (security) support [ends in 30 days](https://www.php.net/supported-versions), so maybe you could already mark on `composer.json` that this needs 8.0?

**Comment by skoro** [comment]
#16
